export const genres = {
    komedia : "Komedia",
    lyhytelokuva : "Lyhytelokuva",
    draama : "Draama",
    elamankerta : "Elämänkerta",
    historia : "Historia",
    fantasia : "Fantasia",
    kauhu : "Kauhu",
    perhe : "Perhe",
    romantiikka : "Romantiikka",
    toiminta : "Toiminta",
    seikkailu : "Seikkailu",
    sota : "Sota",
    western : "Western",
    scifi : "Sci-Fi",
    mysteeri : "Mysteeri",
    jannitys : "Jännitys",
    musiikki : "Musiikki",
    musikaali : "Musikaali",
    rikos : "Rikos",
    urheilu : "Urheilu",
    dokumentti : "Dokumentti",
    animaatio : "Animaatio",
    filmnoir : "Film-Noir"
}